apiVersion: apps/v1
kind: Deployment
metadata:
  name: filegator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filegator
  template:
    metadata:
      labels:
        app: filegator
    spec:
      containers:
        - name: filegator
          image: filegator-local:latest
          imagePullPolicy: Never  # Since you're using minikubeâ€™s local image
          ports:
            - containerPort: 8080
            - containerPort: 8081
          volumeMounts:
            - name: frontend-code
              mountPath: /var/www/filegator/frontend
            - name: backend-code
              mountPath: /var/www/filegator/backend
            - name: ini-file
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: config
              mountPath: /var/www/filegator/configuration.php
              subPath: configuration.php
            - name: file-data
              mountPath: /var/www/filegator/repository
      volumes:
        - name: frontend-code
          hostPath:
            path: "/mnt/d/14 9 13 9 20/Projects/Ticketing System/TicketingSystem/filegator/frontend"
            type: Directory
        - name: backend-code
          hostPath:
            path: "/mnt/d/14 9 13 9 20/Projects/Ticketing System/TicketingSystem/filegator/backend"
            type: Directory
        - name: ini-file
          configMap:
            name: filegator-config
            items:
              - key: php.ini
                path: php.ini
        - name: config
          configMap:
            name: filegator-config
            items:
              - key: configuration.php
                path: configuration.php
        - name: file-data
          persistentVolumeClaim:
            claimName: filegator-repository-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: filegator-service
spec:
  selector:
    app: filegator
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
    - port: 8081
      targetPort: 8081
      nodePort: 30081
