security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:change-me-change-me-change-me-change-me}
    expirationMinutes: ${SECURITY_JWT_EXPIRATION_MINUTES:60}
    bypass: ${SECURITY_JWT_BYPASS:true}

---
spring:
  config:
    activate:
      on-profile: prod
security:
  jwt:
    bypass: false
    expirationMinutes: ${SECURITY_JWT_EXPIRATION_MINUTES:60}
